### ISSUE TITLE
CircleCI: false positive result

### ISSUE THREAD

**Issue by artemgurzhii** [garris/BackstopJS#1145]
I'm trying to integrate BackstopJS with the CircleCI and having a problem with receiving a false-positive result. 
 - I have 104 tests, 395 occurrences of `compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 0.14%, threshold: 1e-7% }: some-image.png` and tests are passing successfully. 
 - I'm removing all of the tests except one or two - they fail(as expected)

there is no difference between first and second run, except the number of test cases.

**config:**
```json
{
  "id": "some_id",
  "onReadyScript": "som_js_script.js",
  "viewports": [
    {
      "name": "1680",
      "width": 1680,
      "height": 4000
    },
    {
      "name": "1920",
      "width": 1920,
      "height": 4000
    },
    {
      "name": "2560",
      "width": 2560,
      "height": 4000
    }
  ],
  "scenarios": [
    {
      "label": "scaffolding",
      "url": "path_for_the_first_test.html",
      "selectors": ["document"],
      "misMatchThreshold": 0.0000001,
      "delay": 1000,
      "viewports": [
        {
          "label": "Default",
          "width": 1920,
          "height": 4000
        }
      ]
    },
 ],
 "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts/puppet/",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": ["CI"],
  "engineOptions": {
    "args": ["--no-sandbox"]
  },
  "engine": "puppeteer",
  "asyncCaptureLimit": 5
}
```

and also, as test completes successfully - there is no artifacts.

**ENV:**
All tests are running on the CircleCI
node: circleci/node:8.15.0-jessie

**Comment by artemgurzhii** [comment]
So here are results of my research, ff any scenario does not have `viewports` field - tests passing successfully even if errors present.

So, I have added 
```
"viewports": [{
  "label": "Default",
  "width": 1920,
  "height": 4000
}]
```
to each scenario that didn't have it and all is working now as expected. 
Please, add a `bug` label to the issue.

**Comment by artemgurzhii** [comment]
adding [here](https://github.com/garris/BackstopJS/blob/master/core/util/compare/index.js#L77) 

```js
reject(data);
```
fixed problem for me(at least for now, can give more info with time)

**Comment by sashamorozov** [comment]
Hi @garris, any updates?

I found that the script does not go into `then` after `compare`, and therefore there is no fail status.
https://github.com/garris/BackstopJS/blob/39ef813a863f1dc81f94e4c068f25150249c0b0c/core/command/report.js#L173

![image](https://user-images.githubusercontent.com/4144548/77310976-4e5f6380-6d10-11ea-9ece-5fa217629508.png)

**Comment by artemgurzhii** [comment]
none of those options worked for us so here is the final version which is working until we have that bug fixed

in the `.circleci/config.yml` when running task instead of using `command: yarn some_command_name` use `command: ./scripts/circleci/run_tests`.

You need to create `scripts/circleci/run_tests`(below you will see the content of that file) and `tmp/backstop_report.txt`(this one should be empty).

Here is the content of the `./scripts/circleci/run_tests` file.

```bash
#!/usr/bin/env bash

set -e

yarn some_command_name > tmp/backstop_report.txt # redirect output to the file

# log that to the console so you can see how everything went
cat tmp/backstop_report.txt

# If there are any matched of the word "ERROR" - exit with the fail status
if [ "$(grep -c "ERROR" tmp/backstop_report.txt)" -ge 1 ]; then # check if there is any error in the tmp file
  echo "NOT OK: Tests failed";

  # exit with the fail status
  exit 127;
else
  echo "OK: Tests passed";
fi
```

**Comment by comzeradd** [comment]
> adding [here](https://github.com/garris/BackstopJS/blob/master/core/util/compare/index.js#L77)
> 
> ```js
> reject(data);
> ```
> 
> fixed problem for me(at least for now, can give more info with time)

That seems like a good catch, but it didn't solve the problem?

**Comment by artemgurzhii** [comment]
@comzeradd Hi, nope, I thought that it worked, but it didn't actually. Above a I have added a bash script that we currently use as the fix for that bug

**Comment by cvolpe-ecobee** [comment]
@garris Do you know if this bug has or will be addressed? 

I started experiencing this issue. For now, I will implement the workaround and see if it works 👍

**Comment by nonAlgebraic** [comment]
Here's a solution I implemented in a Node script that runs backstop, as an alternative to the "bash wrapping script" solution above:

```JavaScript
// will be used to detect when the call to backstop() does not return a promise
// or if it does but the promise is never settled
let didSettle = false

backstop(...your args)
  .then(() => {
    // the promise is settled (with no test failures)
    didSettle = true
    process.exit(0)
  })
  .catch(() => {
    // the promise is settled (with test failures)
    didSettle = true
    process.exit(1)
  })

process.on('exit', () => {
  if (!didSettle) {
    // didSettle is still set to false. this means that the call to backstop()
    // either never returned a promise, or that the promise it returned was never
    // settled (was never resolved or rejected)
    process.exit(1)
  }
})
```
