### ISSUE TITLE
Having trouble generating ci_report

### ISSUE THREAD

**Issue by mousemke** [garris/BackstopJS#210]
I'm trying to generate ci reports to integrate with jenkins, but whatever i try, i cant get it to output a file.  I've added "CI" to the `json`, as well as changing the directory repeatedly.  it wont generate a report and doesnt throw an error

vague prob, i know, but i can provide code if necessary.

**Comment by garris** [comment]
What version are you using?

**Comment by mousemke** [comment]
`^1.3.2`

**Comment by garris** [comment]
@mousemke could you please post your config file and any other info here. 

@nobso Since this is your feature, would you mind taking a quick look?

**Comment by mousemke** [comment]
mostly default https://gist.github.com/mousemke/77e08417d3c6b3852481b75d51e89a3c

but i've toyed with plenty of options (setting the directories, doing `["CI"]` only, etc)

**Comment by nobso** [comment]
@mousemke, Where have you been looking for a generated file? The report will be generated when you run 'npm run test'.

Can you please add the path for CI report and look at the path?

```
"paths": {
       "ci_report" :  "../../backstop_data/ci_report"
},
```

**Comment by mousemke** [comment]
still the same result.  no ci_report anything (searched whole drive, for the sake of it)

also for the sake of it, my package.json script
`"test:visual:cli": "npm run test:visual:clean && cd node_modules/backstopjs/ && npm run test"`

**Comment by mousemke** [comment]
output (report changed to just "CI" for brevity.  no mention of ci, no errors)

```
➜  backoffice git:(master) ✗ npm run test:visual:cli

> backoffice@0.0.1 test:visual:cli /Library/WebServer/Documents/backoffice
> npm run test:visual:clean && cd node_modules/backstopjs/ && npm run test


> backoffice@0.0.1 test:visual:clean /Library/WebServer/Documents/backoffice
> cd node_modules/backstopjs/ && rm -rf bitmaps_test


> backstopjs@1.3.2 test /Library/WebServer/Documents/backoffice/node_modules/backstopjs
> gulp test


BackstopJS Config loaded at location /Library/WebServer/Documents/backoffice/backstop.json
(node:4503) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[18:23:44] Using gulpfile /Library/WebServer/Documents/backoffice/node_modules/backstopjs/gulpfile.js
[18:23:44] Starting 'init'...
[18:23:44] Finished 'init' after 90 μs
[18:23:44] Starting 'test'...

Running CasperJS with:  [ 'capture/genBitmaps.js' ]
[18:23:44] Finished 'test' after 10 ms
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for desktop (1920x1080)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for phone (320x480)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for tablet_v (568x1024)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for tablet_h (1024x768)
CasperJS: Comparison config file updated.

Bitmap file generation completed.
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[18:23:54] Starting 'start'...
[18:23:55] Finished 'start' after 1 s
[18:23:55] Starting 'report'...
[18:23:55] Finished 'report' after 22 μs
```

**Comment by nobso** [comment]
@mousemke From this log, i don't see the 'compare' task running. Can you confirm that ?

**Comment by nobso** [comment]
@mousemke I think, i got the issue and it seems like there is a bug. Let me fix and raise a PR.

**Comment by mousemke** [comment]
seems confirmed

![console](https://cloud.githubusercontent.com/assets/1480168/16391169/39595cb4-3ca6-11e6-925c-a6ede9789006.png)


```
> backoffice@0.0.1 test:visual:cli /Library/WebServer/Documents/backoffice
> npm run test:visual:clean && cd node_modules/backstopjs/ && npm run test


> backoffice@0.0.1 test:visual:clean /Library/WebServer/Documents/backoffice
> cd node_modules/backstopjs/ && rm -rf bitmaps_test


> backstopjs@1.3.2 test /Library/WebServer/Documents/backoffice/node_modules/backstopjs
> gulp test


BackstopJS Config loaded at location /Library/WebServer/Documents/backoffice/backstop.json
(node:5141) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[20:15:06] Using gulpfile /Library/WebServer/Documents/backoffice/node_modules/backstopjs/gulpfile.js
[20:15:06] Starting 'init'...
[20:15:06] Finished 'init' after 92 μs
[20:15:06] Starting 'test'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[20:15:06] Starting 'bless'...
[20:15:06] Finished 'bless' after 4.03 ms

Running CasperJS with:  [ 'capture/genBitmaps.js' ]
[20:15:06] Finished 'test' after 13 ms
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for desktop (1920x1080)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for phone (320x480)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for tablet_v (568x1024)
CasperJS: Ready event received.
CasperJS: Current location is ../../dist/index.html
CasperJS: Screenshots for tablet_h (1024x768)
CasperJS: Comparison config file updated.

Bitmap file generation completed.
[20:15:16] Starting 'start'...
[20:15:17] Finished 'start' after 1.01 s
[20:15:17] Starting 'report'...
[20:15:17] Finished 'report' after 12 μs
```

i ran `cd node_modules/backstopjs/ && node node_modules/.bin/gulp compare` and it seemed to run the task

```
BackstopJS Config loaded at location /Library/WebServer/Documents/backoffice/backstop.json
(node:5847) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[20:32:49] Using gulpfile /Library/WebServer/Documents/backoffice/node_modules/backstopjs/gulpfile.js
[20:32:49] Starting 'compare'...
***************** compare *****************
 OK: Styla Backoffice 0_0_backoffice_1_phone.png
 OK: Styla Backoffice 0_0_backoffice_2_tablet_v.png
 OK: Styla Backoffice 0_0_backoffice_3_tablet_h.png
 OK: Styla Backoffice 0_0_backoffice_0_desktop.png
 OK: Styla Backoffice 0_1_body_1_phone.png
 OK: Styla Backoffice 0_1_body_2_tablet_v.png
 OK: Styla Backoffice 0_1_body_3_tablet_h.png
 OK: Styla Backoffice 0_1_body_0_desktop.png

Test completed...
 8 Passed
 0 Failed
```

**Comment by nobso** [comment]
@mousemke can you apply https://github.com/garris/BackstopJS/pull/211/files change and test ?

**Comment by mousemke** [comment]
that does the trick.  thanks!

**Comment by nobso** [comment]
Cool! Thanks for verifying the changes and sorry for the inconvenience! If @garris merges https://github.com/garris/BackstopJS/pull/211, we all would have that issue fixed in the next version.

**Comment by garris** [comment]
@mousemke Thank you for reporting the issue and helping us to troubleshoot!
@nobso Thanks!  Will merge now...

**Comment by nobso** [comment]
@mousemke Thanks for reporting it.

**Comment by mousemke** [comment]
@nobso @garris no worries!  love to help.

**Comment by mousemke** [comment]
just a heads up.  file writing works, but it's still not running the compare task.  as a stop gap measure i'm just using 
`"test:visual:cli": "npm run test:visual:clean && cd node_modules/backstopjs/ && npm run test && ../.bin/gulp compare"`

**Comment by nobso** [comment]
@mousemke  ```npm run test``` should take care of that comparison.

**Comment by garris** [comment]
@mousemke did that take care of your issue?

**Comment by mousemke** [comment]
Yup. Sorry for no reply. All better!

**Comment by nobso** [comment]
@mousemke Good to hear that! 😄  @garris lets close this issue.

**Comment by garris** [comment]
Thanks guys!  👍
