### ISSUE TITLE
How to run tests locally with docker?

### ISSUE THREAD

**Issue by kyleoliveiro** [garris/BackstopJS#796]
I've got BackstopJS set up and running nicely on our development environments and on our CI pipeline. However, tests are failing because of font inconsistencies between environments (dev=osx, ci=linux).

Seems like running tests locally with Docker is the right solution; However I'm new to Docker and having trouble figuring out how to run BackstopJS tests locally with the Docker image.

Is there any information on how to get started with local Backstop+Docker testing?

**Comment by garris** [comment]
@kyleoliveiro Thanks for posting!   I just tested this and realized that there were issues running docker with the default config -- I don't know if your question was related to this but I have just pushed a fix for that anyway.  So thanks for the report.  

To directly answer your question -- running in docker is pretty easy.  Here is a super fast super simple tutorial...

FYI: Here is where the official image lives...
https://hub.docker.com/r/backstopjs/backstopjs/

1) Make sure docker loaded and running in your env.  On Mac I've enabled the menubar option and it looks like this...
![image](https://user-images.githubusercontent.com/447033/41244103-eb576a8e-6d58-11e8-9f81-b681b3d75eb2.png)

2) Make sure you have the latest backstop image...
```
docker pull backstopjs/backstopjs
```

3) Create a test directory on your desktop (or wherever).  `cd` into there and initialize backstop...
```
docker run --rm -it -v $(pwd):/src backstopjs/backstopjs init
```
Now your directory should look like this...
![image](https://user-images.githubusercontent.com/447033/41244964-8e57a580-6d5b-11e8-9554-af2c71276e27.png)


4) If that last step worked out you are on your way!  Now run the default test...
```
docker run --rm -it -v $(pwd):/src backstopjs/backstopjs test
```
The expected behavior is to get this in your console...
![image](https://user-images.githubusercontent.com/447033/41245097-e9c7a67c-6d5b-11e8-8876-2237d9ac6d79.png)
...and your directory should now have test data...
![image](https://user-images.githubusercontent.com/447033/41245116-f9ea8768-6d5b-11e8-9215-bbff6d3efb42.png)
If you open `backstop_data/html_report/index.html` it should look like this...
![image](https://user-images.githubusercontent.com/447033/41245189-36693f2c-6d5c-11e8-8f13-5803829a1bb6.png)

5) so far so good?  Approve the current results and test again...
```
docker run --rm -it -v $(pwd):/src backstopjs/backstopjs approve
```
then 
```
docker run --rm -it -v $(pwd):/src backstopjs/backstopjs test
```
Your console should run like this...
![image](https://user-images.githubusercontent.com/447033/41245330-9d0b09ae-6d5c-11e8-96b5-65d207bd299a.png)
And opening the html report should look like this...
![image](https://user-images.githubusercontent.com/447033/41245366-b6d00c72-6d5c-11e8-80ff-cfe3613ad2fe.png)


If you noticed that `docker run --rm -it -v $(pwd):/src backstopjs/backstopjs <command>` is what you are calling instead of `backstop <command>` you are completely correct.  You can turn that into a shortcut if you like.  Might be nice to some docker convenience built into backstop itself -- so we could say run, `backstop test --docker-img=backstop/backstopjs`. (or something like that)

How's that?   Is it working?  Please validate!

Thanks!
☮️

**Comment by kyleoliveiro** [comment]
Thanks for the detailed reply and for the awesome tool called BackstopJS!

I've managed to successfully pull the docker image locally and run the tests. Can confirm that the instance of Backstop inside the Docker container is reading my project's `backstop.json` and writing bitmaps to my project's local `backstop_data` folder.

However, with the current setup, Backstop inside Docker does not seem to be able to see the static pages which I am serving locally at `http://localhost:3000`. It was working before with my local instance of Backstop which I installed through npm.

**Comment by garris** [comment]
If you are just using docker out of the box on windows or mac you can use either of these two approaches...

1) http://host.docker.internal:3000
or 
2) http://<your computer's IP address>:3000

**Comment by kyleoliveiro** [comment]
Thanks, works like a charm! Now the only issue is that `http://host.docker.internal:3000` does not resolve on my CI environment as expected. I'm just working around this by using absolute URLs instead. Although if you have a solution for this, that would be great :)

**Comment by garris** [comment]
That’s the correct way.  👍

**Comment by kyleoliveiro** [comment]
Cool, but what about cases where a static server is required? I.e. can't use absolute url?

**Comment by garris** [comment]
Not sure what you mean.  Can you give an example?

Also — I wanted to confirm that the docker approach fixed the cross platform rendering issue?

**Comment by kyleoliveiro** [comment]
Yes, the Docker approach fixed the cross platform discrepancies. Thanks!

Regarding static servers vs absolute urls: I'm currently using Backstop to perform snapshot testing on individual components in a design system. To do this, I have "kitchen sink" pages (.html) that I'm generating with [KSS](https://github.com/kss-node/kss-node) and they look something like this:

![kitchen-sink](https://user-images.githubusercontent.com/4415224/41298693-6d2820b2-6e94-11e8-9ec3-efb4b68e4b4c.png)

The kitchen sink pages showcase each component's different variations and states.

Now heres the issue; In order to display the pseudo-states (`:hover`, `:focus`, etc.), KSS includes some javascript that reads [`document.styleSheets[i].cssRules`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList). To do this, the document needs to be served via a server (in this case, it's a static html file, so its served over a static file server). If I simply open the html pages via Finder, the browser throws an exception due to CORS:

```
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```

In a more general situation, a Backstop user could be simply testing an Express or React app, so the Backstop scenario urls have to be something like `http://localhost:3000/app`; It wouldn't be possible to use absolute urls.

**Comment by garris** [comment]
Sorry,  I still don’t understand the issue.  🤷🏻‍♂️

**Comment by kyleoliveiro** [comment]
Hmm which part is confusing to you? Essentially, I'm testing a project that needs to be served. Therefore, I can't use absolute URL's in my `backstop.json` config.

This works in my local dev environment, but not in CI:
```
"scenarios": [
    {
      "label": "Button",
      "url": "http://host.docker.internal:3000/item-components-button",
      ...
    }
  ]
```

This works in CI, but not in my local dev environment:
```
"scenarios": [
    {
      "label": "Button",
      "url": "http://localhost:3000/item-components-button",
      ...
    }
  ]
```

I am using the `backstopjs/backstopjs` image during the testing stage on my CI.

**Comment by garris** [comment]
There you go!   Now I haz understanding.

Why don't you just use a active config?

See this...
https://github.com/garris/BackstopJS/blob/master/examples/jsBasedConfig/backstopConfig.js

Notice how that is a JS file -- not a JSON file?

So in your case you can add something like this before line 1...
```
const origin = <some environmental test to detect if you're on your CI> ? "http://localhost:3000/" : "http://host.docker.internal:3000/";
```

then, wherever you're specifying your `url` you can do it like this...
```
"scenarios": [
    {
      "label": "Button",
      "url": origin + "item-components-button",
      ...
    }
  ]
```

capisce?

**Comment by kyleoliveiro** [comment]
Brilliant! That will solve my problem. I missed out that section in the docs 😅. That's all for this issue. Thanks again!

**Comment by airtonix** [comment]
@kyleoliveiro In your CI environment how are you persisting the images between each run?

**Comment by kyleoliveiro** [comment]
@airtonix are you referring to the docker image or snapshot images?

**Comment by airtonix** [comment]
@kyleoliveiro the snapshot images.

**Comment by x1c0** [comment]
Hi @garris this is maybe a stupid question, but when I run the tests like you did above:
![](https://user-images.githubusercontent.com/447033/41245097-e9c7a67c-6d5b-11e8-8876-2237d9ac6d79.png)

I don't have the terminal colours.. do you may have an Idea why? I have colours for other commands but not for when running the tests in docker..

I'm using mac os

**Comment by adamchenwei** [comment]
@x1c0 this seems more of a problem with terminal you are using....

**Comment by tehlivi** [comment]
@garris @kyleoliveiro 

I've come up with this solution as an alternative

in config options add/update:

```
"dockerCommandTemplate": 'docker run --rm -i --add-host=host.docker.internal:host-gateway --mount type=bind,source="{cwd}",target=/src backstopjs/backstopjs:{version} {backstopCommand} {args}',
```

* remove `-t` paramater from the default docker command
  * there is a note in the readme about this, but I found it in this [issue](https://github.com/garris/BackstopJS/issues/967)
* add `--add-host=host.docker.internal:host-gateway`
  * `:host-gateway` this only works with Docker v20.10+ (You can read more [here](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/61001152))
